### ISSUE TITLE
Running in Meltano but no data coming back

### ISSUE THREAD

**Issue by RickRen7575** [hotgluexyz/tap-quickbooks#1]
Hello!

We are trying to run a Meltano pipeline using this `tap-quickbooks` tap, but we are getting no data back. We got it to authenticate and it looks like we're selecting specific available tables, but we're not getting any data back. Has this been tested with Meltano? If so, is there someone who could help us with this?

**Comment by RickRen7575** [comment]
@hsyyid helped me out with this one. Looks like it was an issue with Meltano's default behavior that uses the `catalog` parameter, but `tap-quickbooks` requires using the `properties` parameter.

https://meltano.slack.com/archives/C013EKWA2Q1/p1629150244061500

**Comment by dutycycle** [comment]
The Slack message linked above has been auto-deleted due to age, so in case anyone else comes across this issue, one fix is to add `properties` to the `capabilities` configuration in the tap. In `meltano.yaml`:

```
    - name: tap-quickbooks
      variant: hotgluexyz
      capabilities:
        - properties
```

This will indicate to Meltano that the tap uses the older `properties` parameter format for passing in fields to select.
